# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: NGI5NTVlZmIxMWY2OWUzZjk1M2VhMTcyMDM0NjA2NWIyMDEzMzM2MjBiMDZlMGE0ZjI0ZmE2NzQ0ZDAyZWQ5MDE4MTllYTBlMGUwMzVlNjQ2MDdjN2I2ZWVjYTllZmFjZWIzY2ZjNjk0ODhjMmY2MDY3NTJiOGI5YTNmMGJiMDI=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8762/eureka/

encrypt:
  key: AiJjLaJKIvpTcx67bFJejW5xgRWNbDmh

spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: git@github.com:rmatute/esign-cloud-config-public.git
          clone-on-start: true
          ignore-local-ssh-settings: true
          #passphrase: 
          private-key: |
                        -----BEGIN RSA PRIVATE KEY-----
                        MIIJKAIBAAKCAgEAxB9NU8sYlsHpp6DtmfKewP8K6ekGyXFfU0XO/COlr1C8oXdj
                        WCBifsmo++ULvXLJbMuorA7sQAIcEMFGgJX2g0w1lROlzXsbtIILvD9HVOW/DF4P
                        calHyrkLkXnXeGBBXDvXIDC0dj4GO69PhgkueOOtiC34qJ/yUMUi3i0npVYe8k7O
                        e/8KoZWYRZP5GIEVZMJ5xBAavWonVgnqQwosHqSR3u6TDiNpWgEKCiZZZniyJYuQ
                        G2zUlXkS+NfxHLU+9BL05bUP+2oBKrqiH3Q7RoYvEFE9d9Un7ZSMjNxtKmW5o/WH
                        Bj8YbkVINAtkUw9TWjDTjBhL99TdIAfdnS5uwruQPOP+XXDJH+67JTdPJE6Ycyi/
                        JgAZ7VFj+ZNJXbdBZagqGf0xJsROvuyfVmy12JtOV5ds2RUZs0JqGTGf4izvVB2T
                        MHMcGN11n8JO7xchXsD3BGLiQB0SCw6qYiw05JEs7W70gAoAyVVoc5uGZyRfg02z
                        YiGCJy9RjhSmxTV5+P0psx5NqPR4kHV2w1VTIu6HCErWHsYQjddS+MOPnH6/opyW
                        1FeKa5puGld0FniOiRXeFT/C4fH/2I7KjTF4ZIj6znVOeCqCUSlwyLSkiOOu0tww
                        LWlONIR632z++QSSiBbjGPALE2dK1ZFyJp9AQpTe+RDuLbLJGhHIWuMDHXECAwEA
                        AQKCAgAMB6+CmE6l0Lc4ZRKuAsfiJsLQnk6gRKgIP5v2s2kSW+12KhCZ80KXbF9F
                        NEOIF2ZrmgJ6q1+qfXajQHfGo2w/mYkf39inxglpBSEbJvaFKqKRa6Oe4TdaJAel
                        oMeqxpy7v5/uhY5MQnm3Z4WFP0Luf2jBlbBPB6Che7Yr0rE/3wx+6H6Z9Ib+amKw
                        webhrelWCOfXMvWw8LYA/RK1kgYqywV3m0LB90IbFz06aifJtVWYH/ty8zYHBSo4
                        wWY00JlP92m2PWkBjvsLV+9h5otMRCbW5WTT2OteE2KbsVmw5BSDDih+JZimCvHm
                        31wEDEicm6oeSc8/IHt/33ukjJiWlaGtUCjTxqDVfsupNSSHF4vpMQIAMkRxolA3
                        ywjNtUyLhcp7QQVa6s4TbNL8rKr7/r6hkDrQhs+mZXX508P7GUsIjhk7I/IpGtqZ
                        NyQj+Iw+8beqFMbSeBhw5TGc5FcW7SbgSQQv+0tlPlc3BKB1/WLdnOWZzNXD+e8e
                        TZfqoThqGBpbppza8hpe5WpaYqMWLW3t5w7qLug+g+kACmuA5faW6bwsti5dKap3
                        SeXj8FHxSS9tF4JxkUvMFjlVMXEQ3aieo+NI0fShyuaveEiCLjjo7x0dZKzWw6t7
                        70bu6oYABSB1BDFdujQEgIc7a+i922X1YbvmVkYOfk55fGzhAQKCAQEA/PqbgleX
                        c2IQqlqQPpq10VNSA1mFl4RuhZnsziyOENIJW8nBblE3fxHJV1eSUH+mBvtZ1agT
                        4wS68dQS5GaQthi/PTMqmnTOHH6A99D3CkO1W1UfnYtU2OGEaNHa83gCW6K+w7bp
                        I5+HU0h6u5Rtqb6DAK633Cm6zlXI6XQyM2Ysp/j6AYx7ryjM4MngOFno3+uY3C7C
                        xh4mypVbWkSdv7QfxgWhET73kf75g2NblncFP2svnrIKnzyxHqbNYAcV8tJehD1Q
                        a8RAHdyNuNXdAjObpPK2kysG0dq6lVNTFnyMLNJfZVMX1dg8CRNnxSfWbiaIRY+U
                        mBb2uVaptPzFiQKCAQEAxnbgLpHj09flQsZ45oI8TbMf0F6sG97c3oVk8/G3EADB
                        yRCMzwbpZsx7o6Vo8Kzbm4tEIkkuChQhABGcu+orrv84VrWIMPXvf0PJ2ze4lF3S
                        SG1uzfFUysElv2nYGamSNa4B2ArV2a7qRZkiqPUejSthnxcWoRMWC7UyJXPFHedD
                        xDjj2DNzIdIeyVL7P8b+axDoHBICusLuzyC04g/xJwGFXWAjE6m+aUD2RBHi/TpP
                        a2scNVia+D9fWWDrtYiYSKBk9MPtlqhuTgg8EXXepvPBRqXepp280lK7dvJSiq8q
                        1u4zQnq54E08xwy6ERscqu9pbUs7/aHJZ2lMogeGqQKCAQB4U6sMACWlWAudO55I
                        aMX6XqsvtLD6NJ9tJJ2iI0cfcQfKhNhgZHkFE6y0wo5xg4Ww5HUCTwPGg0V4KOsj
                        gDVsp7Cup1uoQ86VdwZY2Sfn1fS5EHANO2yMDBgy0z5Vd8uHUo1yAdo6e3Kehmb6
                        Ocs/ZcJh3LjPG3ojEmKRyBboo7yx2JbxjaR21+07LkpcA0fk2ebHM+ao3UaOLSRa
                        dzChMke6pIrL7StMYf7EI8o4czwnwg/QZ9btjqyga65b8oLaEH2sYI2T9LCag4FV
                        XUPV/D4X4uo8bca8olEFHbDzjSIPX7DIPRGlQUis+HHvMNepZOKEU5rWDHYmCbaG
                        w4QhAoIBAQCNuTY+C1B2ZyYAmVqcwUPu+IsvcWvWOz/eZ8O/sEzZ0LCRtI/ZB0aF
                        cmCYa/aUZ9wrJzhwg3GtINKwCeOzDXZEcVz6DohC7l0otG/ha9kTmiwgLIWD62Jx
                        p5wdJKh9KuqOCsSmUpaD7LS/Hqvxm5lFlkUQJpyySb7kfXBh7lpFEHEEHtwV+Cev
                        by0s92UUFjZ4nooiAXqRg8KlhuWkyV2cTSm/lHd4Ay9GWm2CDoPZ8Vnli4eJUMzZ
                        meetG9k2uWSF+IQfhgqUG5MphhffIBzvfAH5QVnOAbZlO09DkagAATbGZTOVta4m
                        zwEn4567uHCwYGcY9TDR3kbE4h0nV9iBAoIBAH9x263lZDIq785rmwnRdQfWqRdd
                        rg4oHdd9W6E81iXtR8kJGEmtkE/XtwG42+7JPC60wKOPnuodxwb3WbuPr0j29MVR
                        v06I7uo6Ko+vr6kuYrzL/Y5U2gqFwu/VI4sGL4ADBno5hLQHr+ARnJl+BlMRsjvX
                        G98KwHF1INmycuCabBRhCFdj9Zxq4gFk7OCvyjcimBwVaDr3KMXF9KManifelA4+
                        TeEX9owqXeRmWHchOFoAvieRwr6g5p9kfcQXNVTUSyWEJvtJRHOjQPERR3ehz7+M
                        TBFDuTLz7+LaI97MDLoNeXMA80BY47Iv5jlJ1hXkCeNLfPosvHXBLoqE7ro=
                        -----END RSA PRIVATE KEY-----
